### ISSUE TITLE
DON KNOW HOW TO VISUALIZE FRONTEND

### ISSUE THREAD

**Issue by chicco83** [cypheron/xna_rpkgman#11]
i follow the guide but i don't understand how to access the web page.
if i fo to raspberryp:9999 there is no page available
what am i doing wrong?

**Comment by cypheron** [comment]
Use the IP address instead of the hostname, e.g. 192.168.....:9999. Also check if firewall is active on the raspberry with `sudo ufw status` and if so, add an exception for port 9999.

Closing this issue since it's a networking problem.
