### ISSUE TITLE
Buttons block is not fully visible

### ISSUE THREAD

**Issue by kirylh** [cypheron/xna_rpkgman#12]
I could see only 1 button (Pause) for each file. To make it visible I changed style for margin-top for button.prog:

        button.prog {
            float: right;
            margin-top: -15px;
            padding: 0;
        }

**Comment by flurmind** [comment]
Thank's! Work fine.

**Comment by cypheron** [comment]
@kirylh Thanks for your suggestion, if you open a PR i can merge.

**Comment by cypheron** [comment]
Resolved with #13
