### ISSUE TITLE
Any way to implement folder selection of recursive scanning in root folder?

### ISSUE THREAD

**Issue by brinza666** [cypheron/xna_rpkgman#5]
Hello,

Thank you so much for you application, it is exactly what I was looking/waiting for a long time.

Could you please implement (if possible), recursive drill in the root directory, so that it will show all pkg's in subfolders?
Or even better, possibility to select a folder with game you want to send?

I had to change this lines of code : 

  console.log("App listening at http://%s:%s", host, port)
may be
 console.log("App listening at http://"+myaddr)
Otherwise it don't show correct parameters of the running server

**Comment by cypheron** [comment]
Thanks @brinza666 for the feedback.
I've added recursive scan with commit 7db7e168b51f566c8cee3530b33e565256bbd3b7. All subfolders containing pkgs will now show. Also fixed display of server parameters as suggested.

**Comment by brinza666** [comment]
Thank you!
