### ISSUE TITLE
Feature Request: Handle spaces in file path

### ISSUE THREAD

**Issue by KosVas91** [cypheron/xna_rpkgman#6]
Hello. Thank you for great application.
I am using it as a Docker container on my Synology NAS and it works mostly fine. 

The problem I am facing is that I have a quite large game collection, and it is hard to maintain it without using spaces in folder names.  As example, my folder structure is like:
Full Game Name (CUSAXXXXXX) [v01.07]/PSN_STYLED_NAME-A0100-V0100.pkg
As you can see, folder name (but not pkg file name) contains spaces and some special characters. The tests shows that everything works fine if spaces are removed.

With spaces in path I get Error: Unable to set up prerequisites for package 'link to pkg file'. If I try to open "link to pkg file" from browser it working fine.

I understand that this problem is mentioned in 'Troubleshooting', but maybe there is different fix than not using spaces at all?

**Comment by cypheron** [comment]
@KosVas91 Thanks for the suggestion! Support for whitespaces in the filepath has been added in the latest commit (9f4dd78)
