### ISSUE TITLE
Progress panels disappear instantly

### ISSUE THREAD

**Issue by Rast1234** [cypheron/xna_rpkgman#7]
Hi! For some reason panels with progress show for a brief moment and then disappear. This is due to `/status` requests returning `false` quite often, don't know why. Also requests like `/progress/5` are quite slow for me and time out a lot eg. if installer app is closed or not responding. So, requests get created faster than they time out....

I hacked a simple lock (do not make status request if one is running) but not sure how to properly update interface without removing progressbar first...

UPD: implemented fix: instead of hiding tasks on `false` status response, set `opacity: 50%`.

**Comment by cypheron** [comment]
Thanks for reporting the issue and submitting PR! Merged.
